# Generated by Django 4.1.7 on 2023-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cleaning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleaning',
            name='polish',
            field=models.CharField(choices=[('W', 'Wipe'), ('B', 'Brush'), ('S', 'Shine')], default='W', max_length=1),
        ),
    ]
